apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-m77e
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-m77e
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-m77e
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-m77e
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-m77e
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-bundle-tenant/appstudio/dc-metro-map-m77e@sha256:e21fc21c53a419b248f6c5083a54a99e8e86dca05cd3d6e239d2325525d775db
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
